
export const database = [
{ 
    id: 1,
    foto: 'https://i.imgur.com/gbm9gGR.png', 
    nome: 'Guilherme Dideco', 
    cargo: 'Modelo',
    idade: '19 anos',
    altura: '1,81',
    cidade: 'Petropolis RJ',
    peso: '65kg',
    view: '10279',
    seguidores: '6994',
    seguindo: '647',
    trab: 'LOJA PIRULITO',
    imgTrab: 'https://gpsanuncio.com.br/wp-content/uploads/2018/04/Pirulito-1.jpg',
    anoTrab: '2019',
    trab2: 'RIO CONSULT',
    imgTrab2: 'http://www.rioconsult.net.br/wp-content/uploads/2016/05/logo-rioconsult.png',
    anoTrab2: '2020'
},
{ 
    id: 2, 
    foto: 'https://i.imgur.com/bDE9gSJ.png', 
    nome: 'Lucas Ferreira Seixas', 
    cargo: 'Dublê',
    idade: '26 anos',
    altura: '1,88',
    cidade: 'Niteroi   RJ',
    peso: '60kg',
    view: '684',
    seguidores: '429',
    seguindo: '190',
    trab: 'PESADELO NA COZINHA',
    imgTrab: 'https://upload.wikimedia.org/wikipedia/pt/5/59/Pesadelo_na_Cozinha.jpg',
    anoTrab: '2019',
    trab2: 'Trabalho lucas 2',
    imgTrab2: 'https://gpsanuncio.com.br/wp-content/uploads/2018/04/Pirulito-1.jpg',
    anoTrab2: '2020'
},
{       
    id: 3, 
    foto: 'https://i.imgur.com/C9t0l2D.png', 
    nome: 'Luis Felipe Saldanha', 
    cargo: 'Ator',
    idade: '22 anos',
    altura: '1,92',
    cidade: 'Petropolis RJ',
    peso: '70kg',
    view: '1073',
    seguidores: '740',
    seguindo: '618',
    trab: 'Trabalho luis 1',
    imgTrab: 'https://gpsanuncio.com.br/wp-content/uploads/2018/04/Pirulito-1.jpg',
    anoTrab: '2020',
    trab2: 'Trabalho luis 2',
    imgTrab2: 'https://gpsanuncio.com.br/wp-content/uploads/2018/04/Pirulito-1.jpg',
    anoTrab2: '2021'
},
{   
    id: 4, 
    foto: 'https://i.imgur.com/co9KmHk.png', 
    nome: 'Igor Haubrich', 
    cargo: 'BodyBuilder',
    idade: '30 anos',
    altura: '1,60',
    cidade: 'Petropolis RJ',
    peso: '90kg',
    view: '745',
    seguidores: '487',
    seguindo: '410',
    trab: 'Trabalho igor 1',
    imgTrab: 'https://gpsanuncio.com.br/wp-content/uploads/2018/04/Pirulito-1.jpg',
    anoTrab: '2019',
    trab2: 'Trabalho leandro 2',
    imgTrab2: 'https://gpsanuncio.com.br/wp-content/uploads/2018/04/Pirulito-1.jpg',
    anoTrab2: '2020'
},
{   
    id: 5, 
    foto: 'https://i.imgur.com/RFRWJz3.jpg', 
    nome: 'Leandro Almeida', 
    cargo: 'Contador',
    idade: '55 anos',
    altura: '1,83',
    cidade: 'Petropolis RJ',
    peso: '90kg',
    view: '810',
    seguidores: '410',
    seguindo: '842',
    trab: 'SEBRAE RIO',
    imgTrab: 'https://diariodorio.com/wp-content/uploads/2020/08/sebrae-rj-800x445-1-1280x720.jpg',
    anoTrab: '2019',
    trab2: 'RIO CONSULT',
    imgTrab2: 'http://www.rioconsult.net.br/wp-content/uploads/2016/05/logo-rioconsult.png',
    anoTrab2: '2021'
},

];