
export const database = [
{ 
    id: 1,
    foto: 'https://i.imgur.com/gbm9gGR.png', 
    nome: 'Guilherme Dideco', 
    cargo: 'Modelo',
    idade: '19 anos',
    altura: '1,81m',
    cidade: 'Petrópolis RJ',
    peso: '65kg',
    view: '10279',
    seguidores: '6994',
    seguindo: '647',
    trab: 'LOJA PIRULITO',
    imgTrab: 'https://gpsanuncio.com.br/wp-content/uploads/2018/04/Pirulito-1.jpg',
    anoTrab: '2019',
    trab2: 'RIO CONSULT',
    imgTrab2: 'http://www.rioconsult.net.br/wp-content/uploads/2016/05/logo-rioconsult.png',
    anoTrab2: '2020'
},
{ 
    id: 2, 
    foto: 'https://i.imgur.com/bDE9gSJ.png', 
    nome: 'Lucas Ferreira Seixas', 
    cargo: 'Dublê',
    idade: '26 anos',
    altura: '1,88m',
    cidade: 'Nikití',
    peso: '60kg',
    view: '684',
    seguidores: '429',
    seguindo: '190',
    trab: 'PESADELO NA COZINHA',
    imgTrab: 'https://upload.wikimedia.org/wikipedia/pt/5/59/Pesadelo_na_Cozinha.jpg',
    anoTrab: '2021',
    trab2: 'BELA ADORMECIDA',
    imgTrab2: 'https://www.abcdobebe.com/wp-content/uploads/2011/05/A-Bela-adormecida.jpg',
    anoTrab2: '2021'
},
{       
    id: 3, 
    foto: 'https://i.imgur.com/C9t0l2D.png', 
    nome: 'Luis Felipe Saldanha', 
    cargo: 'Ator',
    idade: '25 anos',
    altura: '2,10m',
    cidade: 'Petrópolis RJ',
    peso: '32kg',
    view: '1073',
    seguidores: '2045',
    seguindo: '180',
    trab: 'IMITOSE',
    imgTrab: 'https://i.ytimg.com/vi/tE8PyFIxT7M/hqdefault.jpg',
    anoTrab: '2016',
    trab2: 'TIKTOKER',
    imgTrab2: 'https://miro.medium.com/max/1400/1*Xq76S21Lmnu1HxcOPdAnGQ.jpeg',
    anoTrab2: '2021'
},
{   
    id: 4, 
    foto: 'https://i.imgur.com/co9KmHk.png', 
    nome: 'Igor Haubrich', 
    cargo: 'Bodybuilder',
    idade: '30 anos',
    altura: '1,60m',
    cidade: 'Petrópolis RJ',
    peso: '88kg',
    view: '745',
    seguidores: '487',
    seguindo: '410',
    trab: 'MAROMBEIRO',
    imgTrab: 'https://www.dicasdetreino.com.br/wp-content/uploads/2015/02/Marombas-Homens-com-Pernas-Finas.jpg',
    anoTrab: '2021',
    trab2: 'PROFESSOR',
    imgTrab2: 'https://blog.unicep.edu.br/wp-content/uploads/2019/07/qual-a-importancia-do-professor-na-formacao-do-aluno-935x614.jpg',
    anoTrab2: '2018'
},
{   
    id: 5, 
    foto: 'https://i.imgur.com/RFRWJz3.jpg', 
    nome: 'Leandro Almeida', 
    cargo: 'Consultor',
    idade: '40 anos',
    altura: '1,73',
    cidade: 'Petrópolis RJ',
    peso: '90kg',
    view: '810',
    seguidores: '410',
    seguindo: '842',
    trab: 'UBER',
    imgTrab: 'https://media.hugogloss.uol.com.br/uploads/2019/05/pennsylvania-sues-uber-over-late-breach-notification-showcase_image-7-a-10703-1.jpg',
    anoTrab: '2019',
    trab2: 'RIO CONSULT',
    imgTrab2: 'http://www.rioconsult.net.br/wp-content/uploads/2016/05/logo-rioconsult.png',
    anoTrab2: '2021'
},

];